stages:
    - test

run_java_tests:
    stage: test
    tags:
        - rasp
    script:
        - mvn clean compile
        - mysql -u root iTrust < sql/dropTables.sql
        - mysql -u root iTrust < sql/createTables.sql
        - bash ./genTestData.sh
        - mvn test
        - mvn jacoco:report
        - cat target/site/jacoco/index.html

