stages:
    - build
    - test
    - coverage

compile:
    stage: build
    tags:
        - rasp
    script:
        - mvn clean compile

run_java_tests:
    stage: test
    tags:
        - rasp
    script:
        - mysql -u root iTrust < sql/dropTables.sql
        - mysql -u root iTrust < sql/createTables.sql
        - bash ./genTestData.sh
        - mvn test

check_coverage:
    stage: coverage
    tags:
        - rasp
    script:
        - mvn jacoco:report
        - cat target/site/jacoco/index.html

